// Reveal aninda gosterilen Atatürk sozleri.
export const QUOTES: string[] = [
  "Egemenlik kayıtsız şartsız milletindir.",
  "Ne mutlu Türk'üm diyene!",
  "Hayatta en hakiki mürşit ilimdir.",
  "Yurtta sulh, cihanda sulh.",
  "İstikbal göklerdedir.",
  "Türk, öğün, çalış, güven.",
  "Ordular, ilk hedefiniz Akdeniz'dir, ileri!",
  "Benim naçiz vücudum birgün elbet toprak olacaktır; fakat Türkiye Cumhuriyeti ilelebet payidar kalacaktır.",
  "Milletin bağımsızlığını, yine milletin azim ve kararı kurtaracaktır.",
  "Adalet mülkün temelidir.",
  "Sanatsız kalan bir milletin hayat damarlarından biri kopmuş demektir.",
  "Vatanını en çok seven, görevini en iyi yapandır.",
  "Köylü, milletin efendisidir.",
  "Gençliği yetiştiriniz; onlara ilim ve irfanın müspet fikirlerini veriniz.",
  "Bilelim ki milli benliğini bilmeyen milletler, başka milletlerin avıdır.",
  "Hiçbir şeye ihtiyacımız yok, yalnız bir şeye ihtiyacımız vardır; çalışkan olmak!",
  "Ey Türk gençliği! Birinci vazifen, Türk istiklalini, Türk Cumhuriyetini, ilelebet, muhafaza ve müdafaa etmektir.",
  "Tarih yazmak, tarih yapmak kadar mühimdir; yazan yapana sadık kalmazsa değişmeyen hakikat, insanlığı şaşırtacak bir mahiyet alır.",
  "Bir ulus, sımsıkı birbirine bağlı olmayı bildikçe yeryüzünde onu dağıtabilecek bir güç düşünülemez.",
  "Kültür; okumak, anlamak, görebilmek, görebildiğinden mana çıkarmak, ders almak, düşünmek ve zekayı eğitmektir.",
  "Şefkat ve merhamet insanlık kalbidir.",
  "Özgürlük ve bağımsızlık benim karakterimdir.",
  "Biz cahil dediğimiz zaman, mektepte okumamış olanları kastetmiyoruz; kastettiğimiz ilim, hakikati bilmektir.",
  "Yenilgi yenilgi büyüyen bir zafer vardır.",
  "Siyasi, askeri zaferler ne kadar büyük olurlarsa olsunlar, ekonomik zaferlerle taçlandırılmazlarsa husule gelen zaferler kalıcı olamaz.",
  "Bir millet zenginliğiyle değil, ahlak klasikleriyle ölçülür.",
  "Dünyada her şey için, medeniyet için, hayat için, başarı için en hakiki mürşit ilimdir, fendir.",
  "Öğretmenler! Yeni nesil sizin eseriniz olacaktır.",
  "Muhtaç olduğun kudret, damarlarındaki asil kanda mevcuttur!",
  "Yüksek Türk! Senin için yüksekliğin hududu yoktur; işte parola budur.",
  "Umutsuz durumlar yoktur, umutsuz insanlar vardır; ben hiçbir zaman umudumu kaybetmedim.",
  "Milletimiz her güçlüğe ve zorluğa karşın medeniyet yolunda yürümeye ve ilerlemeye kararlıdır.",
  "Kendiniz için değil, bağlı bulunduğunuz ulus için elbirliğiyle çalışınız; çalışmaların en yükseği budur.",
  "Büyük başarılar, değerli anaların yetiştirdikleri seçkin evlatlar sayesinde olmuştur.",
  "Medeniyet şahlanışı, taklitçilikle olmaz; yaratıcılıkla olur.",
  "Bütün ümidim gençliktedir.",
  "Hayat demek mücadele demektir; hayatta başarı, mutlaka mücadelede başarı kazanmakla mümkündür.",
  "Uygarlık doruğunun merdiveni sanattır.",
  "Fikirler anlamsız amellerle beslenmezse, o fikirler kurur gider.",
  "Türk milleti çalışkandır, Türk milleti zekidir.",
];

export const randomQuote = () => QUOTES[(Math.random() * QUOTES.length) | 0];
